### ISSUE TITLE
Running grunt fails on babel:dist task

### ISSUE THREAD

**Issue by msolberg** [jeremiahbuckley/honeybeevote#1]
I get the following when I run grunt on this project:

```
[msolberg@localhost honeybeevotesvc]$ grunt
Running "babel:files" (babel) task

Running "babel:dist" (babel) task
Warning: Path must be a string. Received undefined Use --force to continue.

Aborted due to warnings.

```

I'm guessing it's the same thing as this:

https://github.com/babel/grunt-babel/issues/31

**Comment by jeremiahbuckley** [comment]
commit 380926b should fix this. Apparently I needed to change a babel config path when I moved code around.
n.b. still don't know what Babel is doing for this project. Probably truly wonderful stuff in the dist/\* directory.
